# -*- coding: utf-8 -*-
"""Copy of 100daysML_DAY20_EDA_UNIVARIATE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ikwGk0Z3OfqcWOx2vxTCpMPMBlNkQK3K
"""

import pandas as pd
import seaborn as sns
df= pd.read_csv('/content/train.csv')
df.head()

"""# **1.CATEGORICAL DATA**

a. Countplot
"""

sns.countplot(df['Embarked'])
#df['Survived'].value_counts().plot(kind='bar')

"""b.PIECHART

"""

df['Sex'].value_counts().plot(kind='pie',autopct='%.2f' )

"""# **2. NUMERICAL DATA**

a. Histogram
"""

import matplotlib.pyplot as plt
plt.hist(df['Age'], bins=5)

"""b. Distplot"""

sns.distplot(df['Age'])

"""c. Boxplot"""

sns.boxplot(df['Age'])

df['Age'].min()

df['Age'].max()

df['Age'].mean()

df['Age'].skew()